baseURL: ""
languageCode: "en-gb"
title: "Sketches of Snoak City"
theme: "paperback"
googleAnalytics: "UA-146012578-1"
uglyurls: true
relativeurls: true
canonifyURLs: true
disableHugoGeneratorInject: true
languageCode: en-us
publishDir: "docs" # for github pages
staticDir:
- static

params:
  keywords: Mythaxis Magazine Science Fiction and Fantasy Modern Fiction
  authorname: Les Sklaroff
  description: Sketches of Snoak City, By Les Sklaroff
  githubusername: mythaxis/SnoakCity

permalinks:
  post: :filename

menu:
  main:
    - name: Home
      url: /
      weight: -10
    - name: Sketches
      url: /contents.html
      weight: -9
    - name: About
      url: /about.html
      weight: -7
    - name: About
      url: /about.html
      weight: -6
  # Sources menu
  sources:
    - name: GitHub
      url: https://github.com/mythaxis/SnoakCity
      weight: -10
    - name: Mythaxis magazine
      url: https://mythaxis.co.uk
      weight: -9
  # Head nav menu
  head:
    - name: Sketches
      url: /contents.html
      weight: -9

